apiVersion: v1
kind: Service
metadata:
  name: {{ template "java.fullname" . }}
  labels:
    app: {{ template "java.name" . }}
    chart: {{ template "java.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  
    {{- if .Values.service.extraInternalPort }}
    - port: {{ .Values.service.extraExternalPort }}
      targetPort: {{ .Values.service.extraInternalPort }}
      protocol: TCP
      name: {{ .Values.service.extraName }}
    {{- end }}

  selector:
    app: {{ template "java.name" . }}
    release: {{ .Release.Name }}
